version: "3.3"
services:
  publisher:
    build: ./Pub
    ports:
      - "80:8000"
    networks:
      - goo

  subscriber:
    build: ./Sub
    restart: always
    networks:
      - goo

networks:
  goo:
    driver: "bridge"